@extends('layouts.app')
@section('title','Kelola Jersey')
@section('content')
@php
    $productionLabels = ['queued' => 'Antrean', 'processing' => 'Diproses', 'ready' => 'Siap diambil', 'delivered' => 'Diserahkan', 'cancelled' => 'Dibatalkan'];
    $productionColors = ['queued' => 'bg-slate-100 text-slate-700', 'processing' => 'bg-blue-100 text-blue-800', 'ready' => 'bg-emerald-100 text-emerald-800', 'delivered' => 'bg-violet-100 text-violet-800', 'cancelled' => 'bg-red-100 text-red-700'];
    $paymentColors = ['Belum Bayar' => 'bg-red-100 text-red-700', 'Cicilan' => 'bg-amber-100 text-amber-800', 'Lunas' => 'bg-emerald-100 text-emerald-800'];
@endphp
<div class="mx-auto max-w-7xl px-4 py-8 md:py-12">
<header class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[.18em] text-emerald-700">Administrasi penjualan</p><h1 class="mt-1 text-3xl font-black tracking-tight text-slate-950 md:text-4xl">Kelola Jersey</h1><p class="mt-2 max-w-2xl text-slate-500">Periksa pembayaran, pantau produksi, dan atur stok dari satu tempat.</p></div><a href="{{route('admin.dashboard')}}" class="rounded-xl border border-slate-300 bg-white px-4 py-2.5 text-sm font-bold text-slate-700 shadow-sm">← Dashboard</a></header>
<section class="mt-8 grid grid-cols-2 gap-3 lg:grid-cols-4">
<a href="{{route('admin.orders')}}" class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-slate-500">Semua pesanan</p><p class="mt-2 text-3xl font-black">{{$summary['all']}}</p></a>
<a href="{{route('admin.orders',['payment'=>'pending'])}}" class="rounded-2xl border border-amber-200 bg-amber-50 p-4 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-amber-700">Perlu diverifikasi</p><p class="mt-2 text-3xl font-black text-amber-950">{{$summary['pendingPayments']}}</p></a>
<a href="{{route('admin.orders',['production'=>'active'])}}" class="rounded-2xl border border-blue-200 bg-blue-50 p-4 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-blue-700">Antrean + proses</p><p class="mt-2 text-3xl font-black text-blue-950">{{$summary['inProduction']}}</p></a>
<a href="{{route('admin.orders',['production'=>'ready'])}}" class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 shadow-sm"><p class="text-xs font-bold uppercase tracking-wide text-emerald-700">Siap diambil</p><p class="mt-2 text-3xl font-black text-emerald-950">{{$summary['ready']}}</p></a>
</section>
<div class="mt-8 flex gap-2 overflow-x-auto border-b border-slate-200"><button type="button" data-admin-tab="orders" class="admin-tab whitespace-nowrap border-b-2 border-emerald-700 px-4 py-3 text-sm font-black text-emerald-800">Pesanan</button>@if(auth()->user()->isSuperAdmin())<button type="button" data-admin-tab="catalog" class="admin-tab whitespace-nowrap border-b-2 border-transparent px-4 py-3 text-sm font-bold text-slate-500">Produk & stok</button>@endif</div>
<section data-admin-panel="orders">
<form method="get" action="{{route('admin.orders')}}" class="mt-6 rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><div class="grid gap-3 md:grid-cols-[minmax(220px,1fr)_200px_200px_auto]">
<label><span class="sr-only">Cari pesanan</span><input type="search" name="q" value="{{$filters['q'] ?? ''}}" placeholder="Cari nomor, nama, atau HP…" class="h-11 w-full rounded-xl border border-slate-300 px-3"></label>
<label><span class="sr-only">Status produksi</span><select name="production" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="">Semua produksi</option><option value="active" @selected(($filters['production'] ?? '')==='active')>Antrean + proses</option>@foreach($productionLabels as $value=>$label)<option value="{{$value}}" @selected(($filters['production'] ?? '')===$value)>{{$label}}</option>@endforeach</select></label>
<label><span class="sr-only">Status pembayaran</span><select name="payment" class="h-11 w-full rounded-xl border border-slate-300 bg-white px-3"><option value="">Semua pembayaran</option><option value="pending" @selected(($filters['payment'] ?? '')==='pending')>Perlu diverifikasi</option><option value="unpaid" @selected(($filters['payment'] ?? '')==='unpaid')>Belum bayar</option><option value="partial" @selected(($filters['payment'] ?? '')==='partial')>Cicilan</option><option value="paid" @selected(($filters['payment'] ?? '')==='paid')>Lunas</option></select></label>
<button class="h-11 rounded-xl bg-emerald-800 px-5 font-black text-white">Terapkan</button></div>
@if(array_filter($filters))<div class="mt-3 flex items-center justify-between gap-3 text-sm"><p class="text-slate-500">Menampilkan {{$orders->total()}} pesanan</p><a href="{{route('admin.orders')}}" class="font-bold text-red-600">Hapus filter</a></div>@endif</form>
<div class="mt-5 hidden overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm lg:block">
@if($orders->isNotEmpty())
<div class="overflow-x-auto"><table class="w-full min-w-[1000px] text-left text-sm">
<thead class="bg-slate-100 text-xs font-black uppercase tracking-wide text-slate-500"><tr><th class="px-4 py-3">Pesanan</th><th class="px-4 py-3">Pemesan</th><th class="px-4 py-3 text-center">Item</th><th class="px-4 py-3">Pembayaran</th><th class="px-4 py-3">Produksi</th><th class="px-4 py-3">Tanggal</th><th class="px-4 py-3 text-right">Aksi</th></tr></thead>
@foreach($orders as $o) @php $pendingPayments=$o->payments->where('status','pending'); @endphp
<tbody class="border-t border-slate-200" data-order-group>
<tr class="align-middle hover:bg-slate-50"><td class="px-4 py-4"><b class="text-slate-950">{{$o->order_number}}</b>@if($pendingPayments->isNotEmpty())<span class="mt-1 block w-fit rounded-full bg-amber-300 px-2 py-0.5 text-[11px] font-black text-amber-950">{{$pendingPayments->count()}} bukti baru</span>@endif</td><td class="px-4 py-4"><b>{{$o->customer_name}}</b><span class="mt-0.5 block text-xs text-slate-500">{{$o->phone}}</span></td><td class="px-4 py-4 text-center"><b>{{$o->items->sum('quantity')}}</b></td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-black {{$paymentColors[$o->payment_status]}}">{{$o->payment_status}}</span><span class="mt-1.5 block text-xs text-slate-500">Sisa ฿{{number_format($o->balance,0,'.',',')}}</span></td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-black {{$productionColors[$o->production_status]}}">{{$productionLabels[$o->production_status]}}</span></td><td class="whitespace-nowrap px-4 py-4 text-slate-600">{{$o->created_at->translatedFormat('d M Y')}}<span class="block text-xs text-slate-400">{{$o->created_at->format('H:i')}}</span></td><td class="px-4 py-4 text-right"><button type="button" data-order-toggle aria-expanded="false" class="rounded-lg border border-emerald-700 px-3 py-2 font-black text-emerald-800 hover:bg-emerald-50">Detail</button></td></tr>
<tr data-order-detail class="hidden"><td colspan="7" class="border-t border-slate-200 bg-slate-50 px-5 py-5"><div class="grid gap-5 xl:grid-cols-[1fr_1.2fr]">
<div><h3 class="font-black text-slate-900">Rincian pesanan</h3><div class="mt-2 divide-y divide-slate-200 rounded-xl border border-slate-200 bg-white px-4">@foreach($o->items as $item)<div class="flex justify-between gap-4 py-3"><span>{{$item->product->name}} · {{$item->model}} · {{$item->sleeve==='short'?'Pendek':'Panjang'}} · {{$item->size->name}}</span><b>× {{$item->quantity}}</b></div>@endforeach</div><p class="mt-3 text-sm text-slate-600"><b>Alamat:</b> {{$o->address}}</p></div>
<div><h3 class="font-black text-slate-900">Pembayaran</h3>@forelse($o->payments as $p)<div class="mt-2 flex flex-wrap items-center gap-2 rounded-xl border {{$p->status==='pending'?'border-amber-300 bg-amber-50':'border-slate-200 bg-white'}} p-3"><b>฿{{number_format($p->amount,0,'.',',')}}</b><span class="rounded-full px-2 py-1 text-xs font-black {{$p->status==='verified'?'bg-emerald-100 text-emerald-800':($p->status==='rejected'?'bg-red-100 text-red-700':'bg-amber-200 text-amber-900')}}">{{['pending'=>'Menunggu','verified'=>'Diterima','rejected'=>'Ditolak'][$p->status]}}</span><a class="font-bold text-emerald-800 underline" href="{{route('admin.payment.proof',$p)}}" target="_blank" rel="noopener">Lihat bukti ↗</a>@if($p->status==='pending')<form method="post" action="{{route('admin.payment.verify',$p)}}" class="ml-auto flex gap-2">@csrf @method('PATCH')<input name="notes" placeholder="Catatan" class="w-36 rounded-lg border bg-white p-2"><button name="status" value="rejected" class="rounded-lg border border-red-300 bg-white px-3 py-2 font-bold text-red-700" onclick="return confirm('Tolak bukti pembayaran ini?')">Tolak</button><button name="status" value="verified" class="rounded-lg bg-emerald-800 px-3 py-2 font-black text-white" onclick="return confirm('Terima pembayaran ini?')">Terima</button></form>@endif</div>@empty<p class="mt-2 rounded-xl border border-dashed border-slate-300 p-4 text-sm text-slate-500">Belum ada pembayaran.</p>@endforelse</div>
</div><form method="post" action="{{route('admin.orders.update',$o)}}" class="mt-5 grid gap-3 border-t border-slate-200 pt-4 md:grid-cols-[220px_1fr_auto]">@csrf @method('PATCH')<label><span class="mb-1 block text-xs font-bold text-slate-500">Status produksi</span><select name="production_status" class="h-11 w-full rounded-xl border bg-white px-3">@foreach($productionLabels as $value=>$label)<option value="{{$value}}" @selected($o->production_status===$value)>{{$label}}</option>@endforeach</select></label><label><span class="mb-1 block text-xs font-bold text-slate-500">Catatan internal</span><input name="notes" value="{{$o->notes}}" placeholder="Contoh: menunggu konfirmasi" class="h-11 w-full rounded-xl border bg-white px-3"></label><button class="self-end rounded-xl bg-slate-900 px-5 py-3 font-black text-white">Simpan perubahan</button></form></td></tr>
</tbody>@endforeach
</table></div>
@else<div class="p-12 text-center"><p class="text-4xl">📋</p><h2 class="mt-3 text-xl font-black">Pesanan tidak ditemukan</h2><p class="mt-1 text-slate-500">Coba ubah pencarian atau filter.</p></div>@endif
</div>
<div class="mt-5 space-y-4 lg:hidden">@forelse($orders as $o) @php $pendingPayments=$o->payments->where('status','pending'); @endphp
<article class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="p-5 md:p-6"><div class="flex flex-wrap items-start justify-between gap-4"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><h2 class="text-lg font-black">{{$o->order_number}}</h2><span class="rounded-full px-2.5 py-1 text-xs font-black {{$productionColors[$o->production_status]}}">{{$productionLabels[$o->production_status]}}</span><span class="rounded-full px-2.5 py-1 text-xs font-black {{$paymentColors[$o->payment_status]}}">{{$o->payment_status}}</span>@if($pendingPayments->isNotEmpty())<span class="rounded-full bg-amber-400 px-2.5 py-1 text-xs font-black text-amber-950">{{$pendingPayments->count()}} bukti baru</span>@endif</div><p class="mt-2 font-bold">{{$o->customer_name}}</p><p class="mt-1 text-sm text-slate-500">{{$o->phone}} · {{$o->created_at->translatedFormat('d M Y, H:i')}}</p></div><div class="text-right"><p class="text-xs font-bold uppercase text-slate-400">Total</p><p class="text-xl font-black text-emerald-950">฿{{number_format($o->total,0,'.',',')}}</p><p class="text-xs text-slate-500">Sisa ฿{{number_format($o->balance,0,'.',',')}}</p></div></div>
<details class="mt-5 rounded-xl bg-slate-50 p-4" @if($pendingPayments->isNotEmpty()) open @endif><summary class="cursor-pointer list-none font-black text-slate-700">Rincian pesanan ({{$o->items->sum('quantity')}} jersey) <span class="float-right text-slate-400">⌄</span></summary><div class="mt-3 divide-y divide-slate-200">@foreach($o->items as $item)<div class="flex justify-between gap-3 py-2 text-sm"><span>{{$item->product->name}} · {{$item->model}} · {{$item->sleeve==='short'?'Lengan pendek':'Lengan panjang'}} · Ukuran {{$item->size->name}}</span><b>× {{$item->quantity}}</b></div>@endforeach<div class="pt-3 text-sm text-slate-600"><b>Alamat:</b> {{$o->address}}</div></div></details>
@if($o->payments->isNotEmpty())<div class="mt-4 space-y-2"><h3 class="text-sm font-black">Pembayaran</h3>@foreach($o->payments as $p)<div class="flex flex-wrap items-center gap-3 rounded-xl border {{$p->status==='pending'?'border-amber-300 bg-amber-50':'border-slate-200 bg-slate-50'}} p-3 text-sm"><b>฿{{number_format($p->amount,0,'.',',')}}</b><span class="rounded-full px-2 py-1 text-xs font-black {{$p->status==='verified'?'bg-emerald-100 text-emerald-800':($p->status==='rejected'?'bg-red-100 text-red-700':'bg-amber-200 text-amber-900')}}">{{['pending'=>'Menunggu','verified'=>'Diterima','rejected'=>'Ditolak'][$p->status]}}</span><a class="font-bold text-emerald-800 underline" href="{{route('admin.payment.proof',$p)}}" target="_blank" rel="noopener">Lihat bukti ↗</a>@if($p->status==='pending')<form method="post" action="{{route('admin.payment.verify',$p)}}" class="ml-auto flex flex-1 flex-wrap justify-end gap-2">@csrf @method('PATCH')<input name="notes" placeholder="Catatan (opsional)" class="min-w-44 flex-1 rounded-lg border p-2"><button name="status" value="rejected" class="rounded-lg border border-red-300 bg-white px-3 py-2 font-bold text-red-700" onclick="return confirm('Tolak bukti pembayaran ini?')">Tolak</button><button name="status" value="verified" class="rounded-lg bg-emerald-800 px-3 py-2 font-black text-white" onclick="return confirm('Terima pembayaran ini?')">Terima</button></form>@endif</div>@endforeach</div>@endif</div>
<form method="post" action="{{route('admin.orders.update',$o)}}" class="grid gap-3 border-t bg-slate-50 p-4 md:grid-cols-[220px_1fr_auto]">@csrf @method('PATCH')<label><span class="mb-1 block text-xs font-bold text-slate-500">Status produksi</span><select name="production_status" class="h-11 w-full rounded-xl border bg-white px-3">@foreach($productionLabels as $value=>$label)<option value="{{$value}}" @selected($o->production_status===$value)>{{$label}}</option>@endforeach</select></label><label><span class="mb-1 block text-xs font-bold text-slate-500">Catatan internal</span><input name="notes" value="{{$o->notes}}" placeholder="Contoh: menunggu konfirmasi" class="h-11 w-full rounded-xl border bg-white px-3"></label><button class="self-end rounded-xl bg-slate-900 px-5 py-3 font-black text-white">Simpan</button></form></article>
@empty<div class="rounded-2xl border border-dashed border-slate-300 bg-white p-12 text-center"><p class="text-4xl">📋</p><h2 class="mt-3 text-xl font-black">Pesanan tidak ditemukan</h2><p class="mt-1 text-slate-500">Coba ubah pencarian atau filter.</p></div>@endforelse</div><div class="mt-6">{{$orders->links()}}</div></section>
@if(auth()->user()->isSuperAdmin())<section data-admin-panel="catalog" class="hidden"><div class="mt-6 grid items-start gap-5 lg:grid-cols-[360px_1fr]">
<form method="post" action="{{route('admin.products.store')}}" class="rounded-2xl border bg-white p-5 shadow-sm">@csrf<h2 class="text-xl font-black">Tambah produk</h2><p class="mt-1 text-sm text-slate-500">Buat jenis jersey beserta ukuran awalnya.</p><label class="mt-5 block text-sm font-bold">Nama produk<input name="name" required placeholder="Jersey Dewasa" class="mt-1.5 w-full rounded-xl border p-3"></label><label class="mt-4 block text-sm font-bold">Harga dasar (THB)<input type="number" name="price" min="0" required placeholder="199" class="mt-1.5 w-full rounded-xl border p-3"></label><label class="mt-4 block text-sm font-bold">Ukuran awal<input name="sizes" required placeholder="S, M, L, XL" class="mt-1.5 w-full rounded-xl border p-3"><span class="mt-1 block text-xs font-normal text-slate-500">Pisahkan dengan koma.</span></label><label class="mt-4 block text-sm font-bold">Deskripsi<textarea name="description" rows="3" class="mt-1.5 w-full rounded-xl border p-3"></textarea></label><button class="mt-5 w-full rounded-xl bg-emerald-800 p-3 font-black text-white">Tambah produk</button></form>
<div class="space-y-4">@foreach($products as $product)<article class="rounded-2xl border bg-white p-5 shadow-sm"><form method="post" action="{{route('admin.products.update',$product)}}" class="grid gap-3 md:grid-cols-2">@csrf @method('PUT')<label class="text-sm font-bold">Nama produk<input name="name" value="{{$product->name}}" required class="mt-1.5 w-full rounded-xl border p-2.5"></label><label class="text-sm font-bold">Harga dasar (THB)<input type="number" name="price" min="0" value="{{$product->price}}" required class="mt-1.5 w-full rounded-xl border p-2.5"></label><label class="text-sm font-bold md:col-span-2">Deskripsi<input name="description" value="{{$product->description}}" class="mt-1.5 w-full rounded-xl border p-2.5"></label><label class="flex items-center gap-2 text-sm font-bold"><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($product->is_active)> Tampilkan ke pembeli</label><button class="rounded-xl bg-slate-900 px-4 py-2.5 font-bold text-white md:justify-self-end">Simpan produk</button></form><div class="mt-5 border-t pt-4"><h3 class="text-sm font-black">Ukuran & stok</h3><div class="mt-3 grid gap-2 sm:grid-cols-2">@foreach($product->sizes as $s)<form method="post" action="{{route('admin.sizes.update',$s)}}" class="flex items-center gap-2 rounded-xl bg-slate-100 p-3">@csrf @method('PATCH')<div class="min-w-12"><b>{{$s->name}}</b>@if($s->price_adjustment>0)<small class="block">+฿{{number_format($s->price_adjustment,0,'.',',')}}</small>@endif</div><input type="number" name="stock" min="0" value="{{$s->stock}}" placeholder="Tak terbatas" class="min-w-0 flex-1 rounded-lg border bg-white p-2"><button class="rounded-lg bg-slate-700 px-3 py-2 text-xs font-bold text-white">Simpan</button></form>@endforeach</div></div><form method="post" action="{{route('admin.sizes.store',$product)}}" class="mt-4 flex flex-wrap gap-2 rounded-xl border border-dashed p-3">@csrf<input name="name" required placeholder="Ukuran baru" class="min-w-28 flex-1 rounded-lg border p-2"><input type="number" name="price_adjustment" value="0" min="0" class="min-w-32 flex-1 rounded-lg border p-2" placeholder="Tambahan harga"><button class="rounded-lg bg-emerald-700 px-4 py-2 font-bold text-white">+ Ukuran</button></form></article>@endforeach</div>
</div></section>@endif
</div>
<script>(()=>{const tabs=document.querySelectorAll('[data-admin-tab]'),panels=document.querySelectorAll('[data-admin-panel]');function activate(name){tabs.forEach(tab=>{const active=tab.dataset.adminTab===name;tab.classList.toggle('border-emerald-700',active);tab.classList.toggle('text-emerald-800',active);tab.classList.toggle('border-transparent',!active);tab.classList.toggle('text-slate-500',!active)});panels.forEach(panel=>panel.classList.toggle('hidden',panel.dataset.adminPanel!==name));if(name==='catalog')history.replaceState(null,'','#catalog');else history.replaceState(null,'',location.pathname+location.search)}tabs.forEach(tab=>tab.addEventListener('click',()=>activate(tab.dataset.adminTab)));if(location.hash==='#catalog')activate('catalog');document.querySelectorAll('[data-order-toggle]').forEach(button=>button.addEventListener('click',()=>{const detail=button.closest('[data-order-group]').querySelector('[data-order-detail]'),open=detail.classList.toggle('hidden')===false;button.setAttribute('aria-expanded',open);button.textContent=open?'Tutup':'Detail'}))})();</script>
@endsection
