@extends('layouts.app')
@section('title','Admin Jersey')
@section('content')
<div class="mx-auto max-w-7xl px-4 py-14"><div class="flex justify-between"><h1 class="text-4xl font-black">Jersey</h1><a href="{{route('admin.dashboard')}}">← Dashboard</a></div>
@if(auth()->user()->isSuperAdmin())<details class="mt-8 rounded-xl bg-white p-6 shadow"><summary class="cursor-pointer text-xl font-bold">Produk, ukuran, dan harga (THB)</summary><form method="post" action="{{route('admin.products.store')}}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf<input name="name" required placeholder="Nama produk" class="rounded border p-2"><input type="number" name="price" min="0" required placeholder="Harga dasar (THB)" class="rounded border p-2"><textarea name="description" placeholder="Deskripsi" class="rounded border p-2"></textarea><input name="sizes" required placeholder="Ukuran dipisah koma: S, M, L, XL" class="rounded border p-2"><button class="rounded bg-emerald-800 p-2 text-white md:col-span-2">Tambah produk</button></form>
<div class="mt-6 space-y-4">@foreach($products as $product)<div class="rounded border p-4"><form method="post" action="{{route('admin.products.update',$product)}}" class="grid gap-2 md:grid-cols-4">@csrf @method('PUT')<input name="name" value="{{$product->name}}" required class="rounded border p-2"><input type="number" name="price" min="0" value="{{$product->price}}" required class="rounded border p-2"><input name="description" value="{{$product->description}}" class="rounded border p-2"><label><input type="hidden" name="is_active" value="0"><input type="checkbox" name="is_active" value="1" @checked($product->is_active)> Aktif</label><button class="rounded bg-slate-800 p-2 text-white">Simpan produk</button></form><div class="mt-4 flex flex-wrap gap-2">@foreach($product->sizes as $s)<form method="post" action="{{route('admin.sizes.update',$s)}}" class="flex items-center gap-2 rounded bg-slate-100 p-2 text-sm">@csrf @method('PATCH')<b>{{$s->name}}</b>@if($s->price_adjustment>0)<span>+฿{{number_format($s->price_adjustment,0,'.',',')}}</span>@endif<input type="number" name="stock" min="0" value="{{$s->stock}}" placeholder="Stok bebas" class="w-24 rounded border p-1.5"><button class="rounded bg-slate-700 px-2 py-1.5 text-white">Simpan stok</button></form>@endforeach</div><form method="post" action="{{route('admin.sizes.store',$product)}}" class="mt-3 flex gap-2">@csrf<input name="name" required placeholder="Ukuran" class="w-28 rounded border p-2"><input type="number" name="price_adjustment" value="0" min="0" class="rounded border p-2"><button class="rounded bg-emerald-700 px-3 text-white">Tambah ukuran</button></form></div>@endforeach</div></details>@endif
<h2 class="mt-10 text-2xl font-black">Pesanan</h2>@forelse($orders as $o)<article class="mt-5 rounded-xl bg-white p-6 shadow"><div class="flex flex-wrap justify-between gap-4"><div><b>{{$o->order_number}} · {{$o->customer_name}}</b><p>{{$o->phone}} · ฿{{number_format($o->total,0,'.',',')}} · <b>{{$o->payment_status}}</b></p>@foreach($o->items as $item)<p class="text-sm text-slate-600">{{$item->product->name}} / {{$item->size->name}} / {{$item->model}} / {{$item->sleeve}} × {{$item->quantity}}</p>@endforeach</div><form method="post" action="{{route('admin.orders.update',$o)}}" class="grid gap-2">@csrf @method('PATCH')<select name="production_status" class="rounded border p-2">@foreach(['queued'=>'Antri','processing'=>'Diproses','ready'=>'Siap','delivered'=>'Diserahkan','cancelled'=>'Dibatalkan'] as $value=>$label)<option value="{{$value}}" @selected($o->production_status===$value)>{{$label}}</option>@endforeach</select><input name="notes" value="{{$o->notes}}" placeholder="Catatan produksi" class="rounded border p-2"><button class="rounded bg-slate-800 p-2 text-white">Simpan status</button></form></div>
<div class="mt-4">@foreach($o->payments as $p)<div class="mt-2 flex flex-wrap items-center gap-3 rounded-lg bg-slate-100 p-3"><span>฿{{number_format($p->amount,0,'.',',')}}</span><b>{{$p->status}}</b><a class="text-emerald-800 underline" href="{{route('admin.payment.proof',$p)}}">Bukti</a>@if($p->status==='pending')<form method="post" action="{{route('admin.payment.verify',$p)}}" class="flex flex-wrap gap-2">@csrf @method('PATCH')<select name="status" class="rounded border p-2"><option value="verified">Verified</option><option value="rejected">Rejected</option></select><input name="notes" placeholder="Catatan" class="rounded border p-2"><button class="rounded bg-emerald-800 px-4 py-2 text-white">Verifikasi</button></form>@endif</div>@endforeach</div></article>@empty<p class="mt-4">Belum ada pesanan.</p>@endforelse<div class="mt-6">{{$orders->links()}}</div></div>
@endsection
