@extends('layouts.app')
@section('title','Checkout Jersey')
@section('content')
<div class="mx-auto max-w-6xl px-4 py-10">
    <div><p class="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Checkout</p><h1 class="mt-1 text-3xl font-black md:text-4xl">Selesaikan pesanan</h1><p class="mt-2 text-slate-500">Periksa jersey dan isi data pemesan sebelum membuat pesanan.</p></div>
    <form method="post" action="{{route('jersey.store')}}" class="mt-8 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_340px]">@csrf
        @foreach($items as $entry)<input type="hidden" name="cart_line_ids[]" value="{{$entry['line']}}">@endforeach
        <div class="space-y-6">
            <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div class="flex items-center justify-between"><h2 class="text-xl font-black">Data pemesan</h2><span class="text-xs text-slate-400">Semua kolom wajib</span></div><div class="mt-5 grid gap-5 md:grid-cols-2"><label class="text-sm font-bold">Nama lengkap<input name="customer_name" value="{{old('customer_name')}}" required maxlength="150" autocomplete="name" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"></label><label class="text-sm font-bold">Nomor HP/WhatsApp<input type="tel" name="phone" value="{{old('phone')}}" required maxlength="30" autocomplete="tel" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"></label><label class="text-sm font-bold md:col-span-2">Alamat lengkap<textarea name="address" required maxlength="1000" rows="4" autocomplete="street-address" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100">{{old('address')}}</textarea></label></div></section>
            <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:p-7"><h2 class="text-xl font-black">Detail jersey</h2><div class="mt-4 divide-y divide-slate-100">@foreach($items as $entry)<div class="flex justify-between gap-4 py-4"><div><b>{{$entry['item']['model']}}</b><p class="mt-1 text-sm text-slate-500">{{$entry['product']->name}} · Ukuran {{$entry['size']->name}} · {{$entry['item']['quantity']}} buah</p></div><b class="whitespace-nowrap">Rp {{number_format($entry['unit']*$entry['item']['quantity'],0,',','.')}}</b></div>@endforeach</div></section>
        </div>
        <aside class="sticky top-24 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg"><div class="p-5"><p class="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Total pesanan</p><div class="mt-5 flex items-end justify-between"><span class="text-sm text-slate-500">{{$items->sum(fn($e)=>$e['item']['quantity'])}} jersey</span><b class="text-2xl text-emerald-950">Rp {{number_format($items->sum(fn($e)=>$e['unit']*$e['item']['quantity']),0,',','.')}}</b></div><button class="mt-6 w-full rounded-xl bg-amber-400 px-5 py-4 font-black text-emerald-950 hover:bg-amber-300">Buat Pesanan →</button><a href="{{route('jersey.cart')}}" class="mt-3 block text-center text-sm font-bold text-emerald-700">Kembali ke keranjang</a><div class="mt-5 rounded-xl bg-emerald-50 p-3 text-xs leading-5 text-emerald-900">🔒 Data hanya digunakan untuk memproses pesanan. Pembayaran dilakukan setelah nomor pesanan tersedia.</div></div></aside>
    </form>
</div>
@endsection
