@extends('layouts.app')
@section('title','Pesan Jersey')
@section('content')
<div class="bg-emerald-950 px-4 py-10 text-white"><div class="mx-auto max-w-6xl"><p class="text-sm font-bold uppercase tracking-[.22em] text-amber-400">Jersey Resmi iSetial Wisdom</p><h1 class="mt-2 text-4xl font-black md:text-5xl">Pilih jersey yang cocok untukmu</h1><p class="mt-3 max-w-2xl text-emerald-100">Pilih model, sesuaikan ukuran dan lengan, lalu isi data pemesan. Maksimal dua jersey dalam satu pesanan.</p></div></div>
<div class="mx-auto max-w-6xl px-4 py-8">@if($products->isEmpty())<div class="rounded-2xl bg-amber-100 p-6">Pemesanan belum dibuka. Silakan hubungi pengurus.</div>@else
<form id="jersey-form" method="post" action="{{route('jersey.store')}}">@csrf
<section aria-labelledby="model-title"><div class="flex items-end justify-between"><div><p class="text-sm font-bold text-emerald-700">LANGKAH 1</p><h2 id="model-title" class="text-2xl font-black">Pilih model</h2></div><span class="hidden text-sm text-slate-500 md:block">Klik model untuk melihat tampilannya</span></div>
<div class="mt-4 grid grid-cols-3 gap-2 rounded-2xl bg-white p-2 shadow-sm" role="tablist">
@foreach(['Pria'=>'model-pria.webp','Wanita'=>'model-wanita.webp','Anak'=>'model-anak.webp'] as $model=>$image)<button type="button" role="tab" data-model="{{$model}}" data-image="{{asset('images/jersey/'.$image)}}" class="model-tab rounded-xl px-3 py-3 text-sm font-bold transition md:text-base {{$loop->first?'bg-emerald-800 text-white':'text-slate-500 hover:bg-emerald-50'}}"><span class="block text-xl md:inline">{{$model==='Pria'?'👕':($model==='Wanita'?'🌿':'⭐')}}</span> {{$model}}</button>@endforeach
</div></section>
<input id="model-input" type="hidden" name="model" value="{{old('model','Pria')}}">
<section class="mt-6 overflow-hidden rounded-3xl bg-white shadow-lg"><div class="grid lg:grid-cols-[1.15fr_.85fr]"><div class="relative bg-gradient-to-br from-stone-100 to-emerald-50 p-4 md:p-8"><span class="absolute left-6 top-6 z-10 rounded-full bg-emerald-950 px-3 py-1 text-xs font-bold text-white">Tampak depan & belakang</span><img id="jersey-image" src="{{asset('images/jersey/model-pria.webp')}}" alt="Jersey model pria" class="aspect-square w-full rounded-2xl object-cover transition-opacity duration-200"></div>
<div class="p-6 md:p-8"><p class="text-sm font-bold text-emerald-700">LANGKAH 2</p><h2 class="mt-1 text-2xl font-black">Atur pesanan</h2><div class="mt-6 grid gap-5">
<label class="font-bold">Produk<select id="product" name="jersey_product_id" class="mt-2 w-full rounded-xl border border-slate-200 bg-white p-3">@foreach($products as $p)<option value="{{$p->id}}" data-price="{{$p->price}}">{{$p->name}}</option>@endforeach</select></label>
<label class="font-bold">Ukuran<div id="size-buttons" class="mt-2 flex flex-wrap gap-2">@foreach($products as $p)@foreach($p->sizes as $s)<button type="button" data-size="{{$s->id}}" data-product="{{$p->id}}" data-adjustment="{{$s->price_adjustment}}" class="size-button min-w-12 rounded-xl border border-slate-200 px-4 py-3 text-sm font-bold hover:border-emerald-700">{{$s->name}}</button>@endforeach @endforeach</div><input id="size-input" type="hidden" name="jersey_size_id" value="{{old('jersey_size_id')}}"></label>
<label class="font-bold">Lengan<div class="mt-2 grid grid-cols-2 gap-2"><label class="cursor-pointer rounded-xl border p-3 text-center has-[:checked]:border-emerald-700 has-[:checked]:bg-emerald-50"><input class="sr-only" type="radio" name="sleeve" value="short" checked> Pendek</label><label class="cursor-pointer rounded-xl border p-3 text-center has-[:checked]:border-emerald-700 has-[:checked]:bg-emerald-50"><input class="sr-only" type="radio" name="sleeve" value="long"> Panjang</label></div></label>
<label class="font-bold">Jumlah<div class="mt-2 flex w-fit items-center overflow-hidden rounded-xl border"><button id="minus" type="button" class="h-12 w-12 text-xl">−</button><input id="quantity" type="number" name="quantity" min="1" max="2" value="1" class="h-12 w-14 border-x text-center font-black [appearance:textfield]"><button id="plus" type="button" class="h-12 w-12 text-xl">+</button></div><small class="mt-1 block font-normal text-slate-500">Maksimal 2 pcs</small></label>
<div class="rounded-2xl bg-emerald-950 p-5 text-white"><p class="text-sm text-emerald-200">Perkiraan total</p><p id="total" class="mt-1 text-3xl font-black">Rp 0</p></div></div></div></div></section>
<section class="mt-8 rounded-3xl bg-white p-6 shadow-lg md:p-8"><p class="text-sm font-bold text-emerald-700">LANGKAH 3</p><h2 class="mt-1 text-2xl font-black">Data pemesan</h2><p class="mt-2 text-slate-500">Dipakai untuk konfirmasi dan mengecek status pesanan.</p><div class="mt-6 grid gap-4 md:grid-cols-2"><label class="font-bold">Nama lengkap<input name="customer_name" value="{{old('customer_name')}}" required class="mt-2 w-full rounded-xl border p-3"></label><label class="font-bold">Nomor HP<input name="phone" value="{{old('phone')}}" required inputmode="tel" class="mt-2 w-full rounded-xl border p-3"></label><label class="font-bold">Tanggal lahir<input type="date" name="birth_date" value="{{old('birth_date')}}" class="mt-2 w-full rounded-xl border p-3"></label><label class="font-bold">Jenis kelamin<select name="gender" class="mt-2 w-full rounded-xl border p-3"><option value="male">Laki-laki</option><option value="female">Perempuan</option></select></label><label class="font-bold md:col-span-2">Alamat<textarea name="address" required rows="3" class="mt-2 w-full rounded-xl border p-3">{{old('address')}}</textarea></label></div><button class="mt-6 w-full rounded-xl bg-amber-400 p-4 text-lg font-black text-emerald-950 shadow hover:bg-amber-300">Buat Pesanan Jersey →</button><p class="mt-3 text-center text-xs text-slate-500">Pembayaran dilakukan setelah nomor pesanan berhasil dibuat.</p></section>
</form>@endif<a href="{{route('jersey.lookup')}}" class="mt-6 block text-center font-bold text-emerald-800">Sudah pernah pesan? Cek status pesanan →</a></div>
<script>
const tabs=[...document.querySelectorAll('.model-tab')],modelInput=document.getElementById('model-input'),image=document.getElementById('jersey-image'),product=document.getElementById('product'),sizeInput=document.getElementById('size-input'),sizeButtons=[...document.querySelectorAll('.size-button')],quantity=document.getElementById('quantity'),total=document.getElementById('total');
function money(value){return new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value)}
function chooseModel(tab){tabs.forEach(t=>t.className=t===tab?'model-tab rounded-xl bg-emerald-800 px-3 py-3 text-sm font-bold text-white transition md:text-base':'model-tab rounded-xl px-3 py-3 text-sm font-bold text-slate-500 transition hover:bg-emerald-50 md:text-base');modelInput.value=tab.dataset.model;image.style.opacity=.25;setTimeout(()=>{image.src=tab.dataset.image;image.alt='Jersey model '+tab.dataset.model.toLowerCase();image.style.opacity=1},120)}
function refreshSizes(){let first=null;sizeButtons.forEach(b=>{const visible=b.dataset.product===product.value;b.hidden=!visible;if(visible&&!first)first=b;b.classList.remove('border-emerald-700','bg-emerald-50')});if(first)chooseSize(first)}
function chooseSize(button){sizeButtons.forEach(b=>b.classList.remove('border-emerald-700','bg-emerald-50'));button.classList.add('border-emerald-700','bg-emerald-50');sizeInput.value=button.dataset.size;updateTotal()}
function updateTotal(){const price=Number(product?.selectedOptions[0]?.dataset.price||0),selected=sizeButtons.find(b=>b.dataset.size===sizeInput?.value),adjustment=Number(selected?.dataset.adjustment||0);if(total)total.textContent=money((price+adjustment)*Number(quantity?.value||1))}
tabs.forEach(t=>t.addEventListener('click',()=>chooseModel(t)));sizeButtons.forEach(b=>b.addEventListener('click',()=>chooseSize(b)));product?.addEventListener('change',refreshSizes);quantity?.addEventListener('change',()=>{quantity.value=Math.max(1,Math.min(2,Number(quantity.value)||1));updateTotal()});document.getElementById('minus')?.addEventListener('click',()=>{quantity.value=Math.max(1,Number(quantity.value)-1);updateTotal()});document.getElementById('plus')?.addEventListener('click',()=>{quantity.value=Math.min(2,Number(quantity.value)+1);updateTotal()});refreshSizes();
</script>
@endsection
