@extends('layouts.app')
@section('title','Pesan Jersey')
@section('content')
@php
$catalog = $products->map(fn ($product) => [
    'id' => $product->id,
    'name' => $product->name,
    'description' => $product->description,
    'price' => (float) $product->price,
    'sizes' => $product->sizes->whereIn('name', ['SS', 'S', 'M', 'L', 'XL', '2XL', '3XL', '4XL', '5XL'])->map(fn ($size) => [
        'id' => $size->id,
        'name' => $size->name,
        'adjustment' => (float) $size->price_adjustment,
        'stock' => $size->stock,
    ])->values(),
])->values();
$cartCount=collect(session('jersey_cart',[]))->sum('quantity');
@endphp
<header class="relative overflow-hidden bg-emerald-950 text-white"><div class="absolute inset-0 hidden opacity-20 md:block" style="background-image:radial-gradient(circle at 85% 20%,#fbbf24 0,transparent 24%),radial-gradient(circle at 10% 90%,#34d399 0,transparent 28%)"></div><div class="relative mx-auto flex max-w-7xl items-center justify-between gap-4 px-4 py-4 md:items-end md:py-14"><div class="max-w-3xl"><span class="hidden rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-amber-300 md:inline-flex">Jersey Resmi iSetial Wisdom</span><h1 class="text-2xl font-black tracking-tight md:mt-4 md:text-5xl"><span class="md:hidden">Pesan Jersey</span><span class="hidden md:inline">Pilih jersey favoritmu</span></h1><p class="mt-3 hidden text-emerald-100 md:block">Tentukan model, ukuran, dan jumlah. Simpan ke keranjang atau langsung checkout.</p></div><a id="cart-button" href="{{route('jersey.cart')}}" aria-label="Buka keranjang, {{$cartCount}} item" class="fixed right-3 top-20 z-30 flex h-12 items-center rounded-full border border-white/30 bg-emerald-900 px-3 font-black text-white shadow-xl backdrop-blur transition hover:bg-emerald-800 md:static md:h-auto md:rounded-2xl md:bg-white/10 md:px-5 md:py-3"><span class="text-xl md:text-base">🛒</span><span class="ml-2 hidden md:inline">Keranjang</span><span id="cart-count" class="ml-1 grid min-w-6 place-items-center rounded-full bg-amber-400 px-1.5 py-1 text-xs text-emerald-950 md:ml-2">{{$cartCount}}</span></a></div></header>
<div class="mx-auto max-w-7xl px-4 py-8 pb-44 md:py-10">
@if($products->isEmpty())<div class="rounded-3xl bg-amber-50 p-8 text-center font-bold">Pemesanan belum dibuka.</div>@else
<form method="post" action="{{route('jersey.cart.add')}}" id="selection-form" class="mx-auto max-w-3xl">@csrf
    <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div id="model-slider" class="relative overflow-hidden bg-[#f1eeea]"><img id="preview" alt="Pratinjau jersey" role="button" tabindex="0" aria-label="Lihat detail foto jersey" class="aspect-square w-full cursor-zoom-in object-contain"><button id="model-prev" type="button" aria-label="Model sebelumnya" class="absolute left-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-2xl font-bold shadow-lg">‹</button><button id="model-next" type="button" aria-label="Model berikutnya" class="absolute right-3 top-1/2 grid h-11 w-11 -translate-y-1/2 place-items-center rounded-full bg-white/90 text-2xl font-bold shadow-lg">›</button><div class="absolute inset-x-0 bottom-0 bg-gradient-to-t from-black/70 to-transparent px-5 pb-5 pt-14 text-white"><p class="text-xs font-bold uppercase tracking-wider text-amber-300">Geser untuk memilih model</p><h2 id="slider-model" class="mt-1 text-2xl font-black"></h2><div id="model-dots" class="mt-3 flex gap-2"></div></div></div><div class="p-5 md:p-7"><input id="product" type="hidden" name="jersey_product_id"><div><span class="text-sm font-bold">Ukuran</span><div id="size-options" class="mt-2 flex flex-wrap gap-2"></div><div class="mt-4"><div class="flex justify-between text-xs font-bold"><span id="stock-label">Stok tersedia</span><span id="stock-count"></span></div><div class="mt-2 h-2 overflow-hidden rounded-full bg-slate-200"><div id="stock-bar" class="h-full rounded-full bg-emerald-500 transition-all duration-300"></div></div></div><details class="mt-5 border-t border-slate-100 pt-4"><summary class="flex cursor-pointer list-none items-center justify-between text-sm font-black text-emerald-800">Panduan ukuran <span class="text-xs font-bold text-slate-400">dalam inci ↓</span></summary><div class="mt-3 overflow-hidden rounded-xl border border-slate-200"><div class="bg-emerald-900 px-4 py-2 text-sm font-black text-white" id="size-chart-title"></div><table class="w-full text-center text-sm"><thead class="bg-slate-100 text-xs uppercase text-slate-500"><tr><th class="px-2 py-2">Ukuran</th><th class="px-2 py-2">Lebar dada</th><th class="px-2 py-2">Panjang</th></tr></thead><tbody id="size-chart-body" class="divide-y divide-slate-100"></tbody></table></div><p class="mt-2 text-xs leading-5 text-slate-500">Lebar dada diukur melintang dari ketiak kiri ke kanan. Bandingkan dengan baju yang nyaman dipakai.</p></details></div><input id="model" type="hidden" name="model"><input id="sleeve" type="hidden" name="sleeve"><input id="size" type="hidden" name="jersey_size_id"></div></section>
    <div class="fixed inset-x-0 bottom-0 z-40 grid grid-cols-2 gap-2 border-t border-slate-200 bg-white p-3 shadow-2xl md:static md:mt-5 md:rounded-2xl md:border md:p-4 md:shadow-sm"><div class="col-span-2 flex items-center justify-between gap-3"><div><p class="text-[10px] font-black uppercase tracking-wider text-slate-400">Jumlah</p><div class="mt-1 flex overflow-hidden rounded-lg border border-slate-300 bg-white"><button id="minus" type="button" class="h-9 w-9 text-lg hover:bg-slate-50">−</button><input id="quantity" name="quantity" type="number" min="1" max="20" value="1" class="h-9 w-11 border-x border-slate-200 text-center text-sm font-black [appearance:textfield]"><button id="plus" type="button" class="h-9 w-9 text-lg hover:bg-slate-50">+</button></div></div><div class="text-right"><p id="variant" class="text-[10px] text-slate-500"></p><p id="subtotal" class="mt-0.5 text-xl font-black text-emerald-950"></p></div></div><button id="buy-button" name="intent" value="buy_now" class="rounded-xl bg-amber-400 px-3 py-3.5 text-sm font-black text-emerald-950 hover:bg-amber-300 disabled:cursor-not-allowed disabled:opacity-50 md:px-5 md:py-4 md:text-base">Bayar Sekarang</button><button id="save-button" name="intent" value="save_cart" class="rounded-xl border-2 border-emerald-800 bg-white px-3 py-3 text-sm font-black text-emerald-800 hover:bg-emerald-50 disabled:cursor-not-allowed disabled:opacity-50 md:px-5 md:py-3.5 md:text-base">Simpan Keranjang</button></div>
</form><div id="image-modal" class="fixed inset-0 z-[70] hidden items-center justify-center bg-black/90 p-3 backdrop-blur-sm md:p-8" role="dialog" aria-modal="true" aria-label="Detail foto jersey"><button id="image-modal-close" type="button" class="absolute right-4 top-4 z-10 grid h-11 w-11 place-items-center rounded-full bg-white text-2xl font-black text-slate-900 shadow-xl" aria-label="Tutup detail foto">×</button><div class="flex max-h-full max-w-5xl flex-col items-center"><img id="detail-image" alt="Detail jersey" class="max-h-[82vh] max-w-full rounded-2xl object-contain shadow-2xl"><p id="detail-caption" class="mt-3 rounded-full bg-white/10 px-4 py-2 text-sm font-black text-white"></p></div></div>@endif
</div>
@if($products->isNotEmpty())
<script>
const catalog=@json($catalog),models={'Lelaki Pendek':{sleeve:'short',label:'Lengan pendek',price:199,image:@json(asset('images/jersey/model-pria-pendek-v2.jpg'))},'Lelaki Panjang':{sleeve:'long',label:'Lengan panjang',price:249,image:@json(asset('images/jersey/model-pria-panjang-v3.jpg'))},'Muslimah':{sleeve:'long',label:'Lengan panjang',price:299,image:@json(asset('images/jersey/model-muslimah-v3.jpg'))}},money=v=>new Intl.NumberFormat('th-TH',{style:'currency',currency:'THB',maximumFractionDigits:0}).format(v);let selectedModel='Lelaki Pendek',selectedSize;
const sizeOrder=['SS','S','M','L','XL','2XL','3XL','4XL','5XL'],sizeCharts={adult:[['SS',34,25],['S',36,26],['M',38,27],['L',40,28],['XL',42,29],['2XL',44,30],['3XL',46,31],['4XL',48,32],['5XL',50,32]],muslimah:[['SS',34,31],['S',36,32],['M',38,33],['L',40,34],['XL',42,35],['2XL',44,36],['3XL',46,37],['4XL',48,38],['5XL',50,39]]};
const product=document.getElementById('product'),quantity=document.getElementById('quantity'),imageModal=document.getElementById('image-modal'),detailImage=document.getElementById('detail-image'),detailCaption=document.getElementById('detail-caption');
const modelNames=Object.keys(models);function renderModels(){const active=modelNames.indexOf(selectedModel),m=models[selectedModel];document.getElementById('preview').src=m.image;document.getElementById('preview').alt=`Jersey ${selectedModel}`;document.getElementById('slider-model').textContent=selectedModel;detailImage.src=m.image;detailImage.alt=`Detail jersey ${selectedModel}`;detailCaption.textContent=selectedModel;document.getElementById('model-dots').innerHTML=modelNames.map((name,index)=>`<button type="button" data-model-index="${index}" aria-label="Pilih ${name}" class="h-2.5 rounded-full transition-all ${index===active?'w-8 bg-amber-400':'w-2.5 bg-white/60'}"></button>`).join('');document.querySelectorAll('[data-model-index]').forEach(button=>button.onclick=()=>{selectedModel=modelNames[Number(button.dataset.modelIndex)];renderModels();update()})}function moveModel(delta){const index=(modelNames.indexOf(selectedModel)+delta+modelNames.length)%modelNames.length;selectedModel=modelNames[index];renderModels();update()}
function renderSizeChart(){const muslimah=selectedModel==='Muslimah',rows=sizeCharts[muslimah?'muslimah':'adult'];document.getElementById('size-chart-title').textContent=muslimah?'Ukuran Muslimah':'Ukuran Lelaki';document.getElementById('size-chart-body').innerHTML=rows.map(([size,chest,length])=>`<tr class="${selectedSize?.name===size?'bg-amber-50 font-black text-emerald-900':''}"><td class="px-2 py-2.5 font-black">${size}</td><td class="px-2 py-2.5">${chest}″</td><td class="px-2 py-2.5">${length}″</td></tr>`).join('')}
function renderProducts(){product.value=catalog[0].id;renderSizes()}
function currentProduct(){return catalog.find(p=>String(p.id)===product.value)||catalog[0]}
function renderSizes(){const p=currentProduct(),selectedId=selectedSize?.id??selectedSize;p.sizes.sort((a,b)=>sizeOrder.indexOf(a.name)-sizeOrder.indexOf(b.name));selectedSize=p.sizes.find(s=>String(s.id)===String(selectedId))||p.sizes[0];document.getElementById('size-options').innerHTML=p.sizes.map(s=>`<button type="button" data-size="${s.id}" aria-pressed="${s.id===selectedSize.id}" class="rounded-xl border px-4 py-2.5 text-sm font-black ${s.id===selectedSize.id?'border-emerald-700 bg-emerald-50 text-emerald-800':'border-slate-200'}">${s.name}</button>`).join('');document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=p.sizes.find(s=>String(s.id)===b.dataset.size);renderSizes()});update()}
function updateStock(){const stock=selectedSize.stock,bar=document.getElementById('stock-bar'),label=document.getElementById('stock-label'),count=document.getElementById('stock-count');bar.classList.remove('bg-emerald-500','bg-amber-400','bg-red-500');if(stock===null){label.textContent='Stok tersedia';count.textContent='Tersedia';bar.style.width='100%';bar.classList.add('bg-emerald-500')}else if(stock===0){label.textContent='Stok habis';count.textContent='0 tersedia';bar.style.width='5%';bar.classList.add('bg-red-500')}else if(stock<=5){label.textContent='Stok hampir habis';count.textContent=`${stock} tersisa`;bar.style.width=`${Math.max(15,stock*12)}%`;bar.classList.add('bg-amber-400')}else{label.textContent='Stok tersedia';count.textContent=`${stock} tersedia`;bar.style.width=`${Math.min(100,40+stock*3)}%`;bar.classList.add('bg-emerald-500')}document.getElementById('buy-button').disabled=stock===0;document.getElementById('save-button').disabled=stock===0}
function update(){const m=models[selectedModel],surcharge=['3XL','4XL','5XL'].includes(selectedSize.name)?20:0,limit=selectedSize.stock===null?20:Math.min(20,Math.max(1,selectedSize.stock)),count=Math.max(1,Math.min(limit,Number(quantity.value)||1));quantity.max=limit;quantity.value=count;document.getElementById('model').value=selectedModel;document.getElementById('sleeve').value=m.sleeve;document.getElementById('size').value=selectedSize.id;document.getElementById('variant').textContent=`${m.label} · Ukuran ${selectedSize.name}${surcharge?' · +฿20':''}`;document.getElementById('subtotal').textContent=money((m.price+surcharge)*count);renderSizeChart();updateStock()}
function flyToCart(button){const source=document.getElementById('preview'),target=document.getElementById('cart-button'),start=button.getBoundingClientRect(),end=target.getBoundingClientRect(),size=84,startX=start.left+start.width/2-size/2,startY=Math.max(12,start.top-size-10),endX=end.left+end.width/2-12,endY=end.top+end.height/2-12,clone=source.cloneNode();Object.assign(clone.style,{position:'fixed',zIndex:60,left:`${startX}px`,top:`${startY}px`,width:`${size}px`,height:`${size}px`,border:'3px solid white',boxShadow:'0 12px 30px rgba(0,0,0,.28)',borderRadius:'1rem',objectFit:'cover',pointerEvents:'none'});document.body.appendChild(clone);const curveX=(startX+endX)/2-50,curveY=Math.max(16,Math.min(startY,endY)-90),animation=clone.animate([{left:`${startX}px`,top:`${startY}px`,width:`${size}px`,height:`${size}px`,transform:'rotate(0deg)',opacity:1},{left:`${curveX}px`,top:`${curveY}px`,width:'58px',height:'58px',transform:'rotate(-10deg)',opacity:.9,offset:.55},{left:`${endX}px`,top:`${endY}px`,width:'24px',height:'24px',transform:'rotate(8deg)',opacity:.15}],{duration:850,easing:'cubic-bezier(.22,.7,.24,1)',fill:'forwards'});animation.onfinish=()=>{clone.remove();target.animate([{transform:'scale(1)'},{transform:'scale(1.22)'},{transform:'scale(1)'}],{duration:380,easing:'ease-out'})}}
const form=document.getElementById('selection-form');form.addEventListener('submit',async event=>{if(event.submitter?.value!=='save_cart')return;event.preventDefault();const button=event.submitter,original=button.textContent;button.disabled=true;button.textContent='Menyimpan…';try{const response=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json','X-Requested-With':'XMLHttpRequest'}}),data=await response.json();if(!response.ok)throw new Error(data.message||'Gagal menyimpan jersey.');document.getElementById('cart-count').textContent=data.cart_count;document.getElementById('cart-button').setAttribute('aria-label',`Buka keranjang, ${data.cart_count} item`);flyToCart(button)}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent=original}});
function openImageDetail(){imageModal.classList.remove('hidden');imageModal.classList.add('flex');document.body.classList.add('overflow-hidden');document.getElementById('image-modal-close').focus()}function closeImageDetail(){imageModal.classList.add('hidden');imageModal.classList.remove('flex');document.body.classList.remove('overflow-hidden');document.getElementById('preview').focus()}document.getElementById('preview').onclick=openImageDetail;document.getElementById('preview').onkeydown=event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();openImageDetail()}};document.getElementById('image-modal-close').onclick=closeImageDetail;imageModal.onclick=event=>{if(event.target===imageModal)closeImageDetail()};document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!imageModal.classList.contains('hidden'))closeImageDetail()});
quantity.onchange=update;document.getElementById('minus').onclick=()=>{quantity.value=Math.max(1,Number(quantity.value)-1);update()};document.getElementById('plus').onclick=()=>{quantity.value=Math.min(20,Number(quantity.value)+1);update()};document.getElementById('model-prev').onclick=()=>moveModel(-1);document.getElementById('model-next').onclick=()=>moveModel(1);let touchStart=0;const slider=document.getElementById('model-slider');slider.addEventListener('touchstart',event=>touchStart=event.changedTouches[0].clientX,{passive:true});slider.addEventListener('touchend',event=>{const distance=event.changedTouches[0].clientX-touchStart;if(Math.abs(distance)>45)moveModel(distance<0?1:-1)},{passive:true});renderModels();renderProducts();
</script>
@endif
@endsection
