@extends('layouts.app')
@section('title','Pesan Jersey')
@section('content')
@php
$catalog = $products->map(fn ($product) => [
    'id' => $product->id,
    'name' => $product->name,
    'description' => $product->description,
    'price' => (float) $product->price,
    'sizes' => $product->sizes->map(fn ($size) => [
        'id' => $size->id,
        'name' => $size->name,
        'adjustment' => (float) $size->price_adjustment,
    ])->values(),
])->values();
$cartCount=collect(session('jersey_cart',[]))->sum('quantity');
@endphp
<header class="relative overflow-hidden bg-emerald-950 text-white"><div class="absolute inset-0 opacity-20" style="background-image:radial-gradient(circle at 85% 20%,#fbbf24 0,transparent 24%),radial-gradient(circle at 10% 90%,#34d399 0,transparent 28%)"></div><div class="relative mx-auto flex max-w-7xl flex-wrap items-end justify-between gap-6 px-4 py-10 md:py-14"><div class="max-w-3xl"><span class="inline-flex rounded-full border border-amber-300/30 bg-amber-300/10 px-3 py-1 text-xs font-bold uppercase tracking-[.18em] text-amber-300">Jersey Resmi iSetial Wisdom</span><h1 class="mt-4 text-4xl font-black tracking-tight md:text-5xl">Pilih jersey favoritmu</h1><p class="mt-3 text-emerald-100">Tentukan model, ukuran, dan jumlah. Simpan ke keranjang atau langsung checkout.</p></div><a href="{{route('jersey.cart')}}" class="relative rounded-2xl border border-white/20 bg-white/10 px-5 py-3 font-black backdrop-blur hover:bg-white/20">🛒 Keranjang <span class="ml-2 rounded-full bg-amber-400 px-2 py-1 text-xs text-emerald-950">{{$cartCount}}</span></a></div></header>
<div class="mx-auto max-w-7xl px-4 py-8 md:py-10">
@if($products->isEmpty())<div class="rounded-3xl bg-amber-50 p-8 text-center font-bold">Pemesanan belum dibuka.</div>@else
<form method="post" action="{{route('jersey.cart.add')}}" id="selection-form" class="grid items-start gap-7 lg:grid-cols-[minmax(0,1fr)_360px]">@csrf
    <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div><p class="text-xs font-black uppercase tracking-[.16em] text-emerald-700">Pilih varian</p><h2 class="mt-1 text-2xl font-black">Model jersey</h2></div><div id="model-options" class="mt-5 grid grid-cols-3 gap-2 md:gap-4"></div><div class="mt-7 grid gap-6 md:grid-cols-2"><label class="text-sm font-bold">Jenis produk<select id="product" name="jersey_product_id" class="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-normal outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"></select><span id="description" class="mt-2 block text-xs font-normal text-slate-400"></span></label><div><span class="text-sm font-bold">Ukuran</span><div id="size-options" class="mt-2 flex flex-wrap gap-2"></div></div></div><div class="mt-7 flex flex-wrap items-center justify-between gap-4 rounded-2xl bg-slate-50 p-4"><div><p class="text-xs font-bold uppercase tracking-wider text-slate-400">Jumlah</p><div class="mt-1 flex overflow-hidden rounded-xl border border-slate-300 bg-white"><button id="minus" type="button" class="h-11 w-11 text-xl hover:bg-slate-50">−</button><input id="quantity" name="quantity" type="number" min="1" max="20" value="1" class="h-11 w-14 border-x border-slate-200 text-center font-black [appearance:textfield]"><button id="plus" type="button" class="h-11 w-11 text-xl hover:bg-slate-50">+</button></div></div><div class="text-right"><p id="variant" class="text-xs text-slate-500"></p><p id="subtotal" class="mt-1 text-2xl font-black text-emerald-950"></p></div></div><input id="model" type="hidden" name="model"><input id="sleeve" type="hidden" name="sleeve"><input id="size" type="hidden" name="jersey_size_id"></section>
    <aside class="sticky top-24 overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg"><img id="preview" alt="Pratinjau jersey" class="aspect-square w-full bg-emerald-50 object-cover"><div class="p-5"><p class="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Pilihan Anda</p><h2 id="summary-model" class="mt-1 text-xl font-black"></h2><p id="summary-detail" class="mt-2 text-sm text-slate-500"></p><div class="mt-5 grid gap-3"><button name="intent" value="buy_now" class="rounded-xl bg-amber-400 px-5 py-4 font-black text-emerald-950 hover:bg-amber-300">Bayar Sekarang</button><button name="intent" value="save_cart" class="rounded-xl border-2 border-emerald-800 px-5 py-3.5 font-black text-emerald-800 hover:bg-emerald-50">🛒 Simpan ke Keranjang</button></div><p class="mt-4 text-center text-xs leading-5 text-slate-400">Item dapat diubah atau dihapus melalui halaman keranjang.</p></div></aside>
</form>@endif
<a href="{{route('jersey.lookup')}}" class="mt-8 block text-center text-sm font-bold text-emerald-800">Cek status pesanan sebelumnya →</a></div>
@if($products->isNotEmpty())
<script>
const catalog=@json($catalog),models={'Lelaki Pendek':{sleeve:'short',label:'Lengan pendek',image:@json(asset('images/jersey/model-pria-pendek-v2.jpg'))},'Lelaki Panjang':{sleeve:'long',label:'Lengan panjang',image:@json(asset('images/jersey/model-pria-panjang-v3.jpg'))},'Muslimah':{sleeve:'long',label:'Lengan panjang',image:@json(asset('images/jersey/model-muslimah-v3.jpg'))}},money=v=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(v);let selectedModel='Lelaki Pendek',selectedSize;
const product=document.getElementById('product'),quantity=document.getElementById('quantity');
function renderModels(){document.getElementById('model-options').innerHTML=Object.entries(models).map(([name,m])=>`<button type="button" data-model="${name}" class="overflow-hidden rounded-2xl border-2 ${name===selectedModel?'border-emerald-700 bg-emerald-50 shadow-sm':'border-slate-200'}"><img src="${m.image}" alt="" class="aspect-[4/3] w-full object-cover"><span class="block p-2 text-xs font-black md:text-sm">${name}</span></button>`).join('');document.querySelectorAll('[data-model]').forEach(b=>b.onclick=()=>{selectedModel=b.dataset.model;renderModels();update()})}
function renderProducts(){product.innerHTML=catalog.map(p=>`<option value="${p.id}">${p.name} — ${money(p.price)}</option>`).join('');renderSizes()}
function currentProduct(){return catalog.find(p=>String(p.id)===product.value)||catalog[0]}
function renderSizes(){const p=currentProduct(),selectedId=selectedSize?.id??selectedSize;selectedSize=p.sizes.find(s=>String(s.id)===String(selectedId))||p.sizes[0];document.getElementById('size-options').innerHTML=p.sizes.map(s=>`<button type="button" data-size="${s.id}" aria-pressed="${s.id===selectedSize.id}" class="rounded-xl border px-4 py-2.5 text-sm font-black ${s.id===selectedSize.id?'border-emerald-700 bg-emerald-50 text-emerald-800':'border-slate-200'}">${s.name}</button>`).join('');document.querySelectorAll('[data-size]').forEach(b=>b.onclick=()=>{selectedSize=p.sizes.find(s=>String(s.id)===b.dataset.size);renderSizes()});update()}
function update(){const p=currentProduct(),m=models[selectedModel],count=Math.max(1,Math.min(20,Number(quantity.value)||1));quantity.value=count;document.getElementById('model').value=selectedModel;document.getElementById('sleeve').value=m.sleeve;document.getElementById('size').value=selectedSize.id;document.getElementById('description').textContent=p.description||'Jersey resmi iSetial Wisdom';document.getElementById('variant').textContent=`${m.label} · Ukuran ${selectedSize.name}`;document.getElementById('subtotal').textContent=money((p.price+Number(selectedSize.adjustment))*count);document.getElementById('preview').src=m.image;document.getElementById('summary-model').textContent=selectedModel;document.getElementById('summary-detail').textContent=`${p.name} · Ukuran ${selectedSize.name} · ${count} buah`}
product.onchange=renderSizes;quantity.onchange=update;document.getElementById('minus').onclick=()=>{quantity.value=Math.max(1,Number(quantity.value)-1);update()};document.getElementById('plus').onclick=()=>{quantity.value=Math.min(20,Number(quantity.value)+1);update()};renderModels();renderProducts();
</script>
@endif
@endsection
