@extends('layouts.app')
@section('title','Pesanan '.$order->order_number)
@section('content')
@php
    $productionLabels = ['queued'=>'Dalam antrean','processing'=>'Sedang diproduksi','ready'=>'Siap diambil','delivered'=>'Selesai','cancelled'=>'Dibatalkan'];
    $productionDescriptions = ['queued'=>'Pesanan Anda sudah diterima dan menunggu giliran produksi.','processing'=>'Tim kami sedang menyiapkan jersey Anda.','ready'=>'Pesanan sudah siap untuk diserahkan.','delivered'=>'Pesanan telah selesai dan diserahkan.','cancelled'=>'Pesanan ini telah dibatalkan.'];
    $productionSteps = ['queued'=>'Pesanan diterima','processing'=>'Produksi','ready'=>'Siap diambil','delivered'=>'Selesai'];
    $currentStep = array_search($order->production_status, array_keys($productionSteps), true);
    $currentStep = $currentStep === false ? -1 : $currentStep;
    $pendingPayment = $order->payments->contains('status', 'pending');
    $qr = \App\Models\Setting::valueOf('payment_qr');
@endphp
<div class="bg-slate-100/70 pb-16">
    <section class="bg-emerald-950 text-white"><div class="mx-auto max-w-6xl px-4 py-8 md:py-12"><a href="{{route('jersey.create')}}" class="inline-flex items-center gap-2 text-sm font-bold text-emerald-200 hover:text-white">← Kembali ke pemesanan jersey</a><div class="mt-6 flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><div class="flex flex-wrap items-center gap-3"><p class="text-xs font-black uppercase tracking-[.18em] text-amber-300">Detail pesanan</p><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-black text-emerald-100">{{$productionLabels[$order->production_status] ?? $order->production_status}}</span></div><div class="mt-2 flex flex-wrap items-center gap-3"><h1 class="text-3xl font-black tracking-tight md:text-5xl">{{$order->order_number}}</h1><button type="button" data-copy-order class="rounded-lg border border-white/20 bg-white/10 px-3 py-2 text-xs font-black hover:bg-white/20" aria-label="Salin nomor pesanan">Salin nomor</button></div><p class="mt-3 text-emerald-100">Dibuat {{$order->created_at->translatedFormat('d F Y, H:i')}} · atas nama <b class="text-white">{{$order->customer_name}}</b></p></div><div class="rounded-2xl border border-white/10 bg-white/10 px-5 py-4 backdrop-blur md:min-w-56 md:text-right"><p class="text-xs font-bold uppercase tracking-wider text-emerald-200">Sisa pembayaran</p><p class="mt-1 text-3xl font-black text-amber-300">฿{{number_format($order->balance,0,'.',',')}}</p><p class="mt-1 text-sm font-bold text-white">{{$order->payment_status}}</p></div></div></div></section>
    <div class="mx-auto max-w-6xl px-4 py-6 md:py-8">
        @if($pendingPayment)<div class="mb-6 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-amber-950"><span class="mt-0.5 text-xl">⏳</span><div><p class="font-black">Bukti pembayaran sedang diperiksa</p><p class="mt-1 text-sm text-amber-800">Kami akan memperbarui saldo setelah pembayaran diverifikasi oleh admin.</p></div></div>@endif
        @if($order->production_status==='cancelled')<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-5 text-red-900"><p class="font-black">Pesanan dibatalkan</p><p class="mt-1 text-sm">Hubungi pengurus jika Anda membutuhkan informasi lebih lanjut.</p></div>@else
        <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:p-7"><div class="flex items-start justify-between gap-4"><div><p class="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Status produksi</p><h2 class="mt-1 text-xl font-black text-slate-950">{{$productionLabels[$order->production_status] ?? $order->production_status}}</h2><p class="mt-1 text-sm text-slate-500">{{$productionDescriptions[$order->production_status] ?? ''}}</p></div><span class="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-emerald-100 text-xl">{{['queued'=>'✓','processing'=>'✦','ready'=>'✓','delivered'=>'✓'][$order->production_status] ?? '•'}}</span></div><div class="mt-7 grid grid-cols-4 gap-2">@foreach($productionSteps as $value=>$label) @php($index=$loop->index)<div class="relative text-center before:absolute before:left-0 before:right-0 before:top-2 before:h-1 before:bg-slate-200 first:before:left-1/2 last:before:right-1/2"><span class="relative mx-auto block h-5 w-5 rounded-full border-4 border-white {{$index <= $currentStep ? 'bg-emerald-600' : 'bg-slate-300'}} shadow-sm"></span><p class="mt-2 text-[10px] font-bold leading-tight {{$index <= $currentStep ? 'text-emerald-800' : 'text-slate-400'}} md:text-xs">{{$label}}</p></div>@endforeach</div></section>
        @endif
        <div class="mt-6 grid items-start gap-6 lg:grid-cols-[minmax(0,1fr)_360px]">
            <div class="space-y-6">
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4 md:px-6"><div><p class="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Pesanan</p><h2 class="mt-1 text-xl font-black">Rincian jersey</h2></div><span class="rounded-full bg-slate-100 px-3 py-1 text-xs font-black text-slate-600">{{$order->items->sum('quantity')}} buah</span></div><div class="divide-y divide-slate-100 px-5 md:px-6">@foreach($order->items as $item)<div class="flex items-start justify-between gap-4 py-5"><div><h3 class="font-black text-slate-950">{{$item->product->name}}</h3><p class="mt-1 text-sm text-slate-500">{{$item->model}} · {{$item->sleeve==='short'?'Lengan pendek':'Lengan panjang'}} · Ukuran {{$item->size->name}}</p><p class="mt-2 text-xs font-bold text-slate-400">฿{{number_format($item->unit_price,0,'.',',')}} × {{$item->quantity}}</p></div><p class="whitespace-nowrap font-black text-emerald-950">฿{{number_format($item->subtotal,0,'.',',')}}</p></div>@endforeach</div><div class="border-t border-slate-100 bg-slate-50 px-5 py-4 md:px-6"><p class="text-xs font-bold uppercase tracking-wide text-slate-400">Alamat pengiriman</p><p class="mt-1 text-sm leading-6 text-slate-700">{{$order->address}}</p><p class="mt-1 text-sm font-bold text-slate-700">{{$order->phone}}</p></div></section>
                <section class="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm md:p-6"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Pembayaran</p><h2 class="mt-1 text-xl font-black">Riwayat pembayaran</h2></div><span class="rounded-full px-3 py-1 text-xs font-black {{$order->payment_status==='Lunas'?'bg-emerald-100 text-emerald-800':'bg-amber-100 text-amber-800'}}">{{$order->payment_status}}</span></div><div class="mt-5 space-y-3">@forelse($order->payments as $payment) @php($paymentLabel=['pending'=>'Menunggu verifikasi','verified'=>'Diterima','rejected'=>'Ditolak'][$payment->status] ?? $payment->status)<div class="flex items-center justify-between gap-4 rounded-2xl border border-slate-200 p-4"><div><p class="font-black">฿{{number_format($payment->amount,0,'.',',')}}</p><p class="mt-1 text-xs text-slate-500">{{$payment->created_at->translatedFormat('d M Y, H:i')}}</p></div><span class="rounded-full px-3 py-1 text-xs font-black {{$payment->status==='verified'?'bg-emerald-100 text-emerald-800':($payment->status==='rejected'?'bg-red-100 text-red-700':'bg-amber-100 text-amber-800')}}">{{$paymentLabel}}</span></div>@empty<div class="rounded-2xl border border-dashed border-slate-300 p-6 text-center"><p class="font-bold text-slate-700">Belum ada pembayaran</p><p class="mt-1 text-sm text-slate-500">Unggah bukti pembayaran melalui formulir yang tersedia.</p></div>@endforelse</div></section>
            </div>
            <aside class="space-y-6 lg:sticky lg:top-24">
                <section class="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-lg"><div class="p-5 md:p-6"><p class="text-xs font-black uppercase tracking-[.14em] text-emerald-700">Ringkasan biaya</p><div class="mt-5 space-y-3 text-sm"><div class="flex justify-between text-slate-500"><span>Total pesanan</span><b class="text-slate-900">฿{{number_format($order->total,0,'.',',')}}</b></div><div class="flex justify-between text-slate-500"><span>Sudah dibayar</span><b class="text-emerald-700">฿{{number_format($order->paid_amount,0,'.',',')}}</b></div><div class="flex items-end justify-between border-t border-slate-200 pt-4"><span class="font-black text-slate-900">Sisa</span><b class="text-2xl text-emerald-950">฿{{number_format($order->balance,0,'.',',')}}</b></div></div></div>
                    @if($order->balance>0)<form method="post" enctype="multipart/form-data" action="{{route('jersey.payment',$order->order_number)}}" class="border-t border-slate-100 bg-slate-50 p-5 md:p-6">@csrf<h2 class="font-black text-slate-950">Kirim bukti pembayaran</h2><p class="mt-1 text-xs leading-5 text-slate-500">Transfer melalui QR, lalu unggah foto bukti pembayaran.</p>@if($qr)<div class="mt-4 rounded-2xl border border-slate-200 bg-white p-3 text-center"><img src="{{asset('storage/'.$qr)}}" alt="QR pembayaran" class="mx-auto h-48 w-48 object-contain"><p class="mt-2 text-xs font-bold text-slate-500">Pindai untuk membayar</p></div>@endif<label class="mt-4 block text-sm font-bold">Jumlah pembayaran<div class="relative mt-2"><span class="absolute left-4 top-1/2 -translate-y-1/2 font-black text-slate-500">฿</span><input type="number" name="amount" min="1" max="{{$order->balance}}" value="{{old('amount',$order->balance)}}" required class="w-full rounded-xl border border-slate-300 py-3 pl-9 pr-4 font-black outline-none focus:border-emerald-600 focus:ring-4 focus:ring-emerald-100"></div></label><label class="mt-4 block text-sm font-bold">Foto bukti<input type="file" name="proof" accept="image/*" required class="mt-2 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm file:mr-3 file:rounded-lg file:border-0 file:bg-emerald-100 file:px-3 file:py-2 file:font-bold file:text-emerald-800"></label><button class="mt-5 w-full rounded-xl bg-amber-400 px-5 py-4 font-black text-emerald-950 shadow-sm hover:bg-amber-300">Kirim Bukti Pembayaran →</button></form>@else<div class="border-t border-emerald-200 bg-emerald-50 p-5 text-center text-emerald-900"><div class="text-2xl">✓</div><p class="mt-1 font-black">Pembayaran lunas</p><p class="mt-1 text-xs">Terima kasih, pembayaran Anda telah selesai.</p></div>@endif
                </section>
                <div class="rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm leading-6 text-emerald-900"><b>Butuh bantuan?</b><br>Simpan nomor pesanan <b>{{$order->order_number}}</b> saat menghubungi pengurus.</div>
            </aside>
        </div>
    </div>
</div>
<script>document.querySelector('[data-copy-order]')?.addEventListener('click',async event=>{await navigator.clipboard.writeText(@json($order->order_number));const button=event.currentTarget,original=button.textContent;button.textContent='Tersalin ✓';setTimeout(()=>button.textContent=original,1800)});</script>
@endsection
