@extends('layouts.app')
@section('title','Admin Struktur')
@section('content')
<div class="mx-auto max-w-7xl px-4 py-12"><div class="flex justify-between"><h1 class="text-4xl font-black">Struktur & DKM</h1><a href="{{route('admin.dashboard')}}">← Dashboard</a></div>
<div class="mt-8 grid gap-5 lg:grid-cols-3"><form method="post" action="{{route('admin.periods.store')}}" class="grid gap-3 rounded-xl bg-white p-5 shadow">@csrf<h2 class="text-xl font-bold">Periode</h2><select name="masjid_id" class="rounded border p-2">@if($canGlobal)<option value="">iSetial Wisdom</option>@endif @foreach($masjids as $m)<option value="{{$m->id}}">DKM {{$m->name}}</option>@endforeach</select><input name="name" required placeholder="2026–2029" class="rounded border p-2"><input type="date" name="starts_at" required class="rounded border p-2"><input type="date" name="ends_at" class="rounded border p-2"><input type="hidden" name="is_active" value="1"><button class="rounded bg-emerald-800 p-2 text-white">Tambah periode</button></form>
<form method="post" action="{{route('admin.positions.store')}}" class="grid gap-3 rounded-xl bg-white p-5 shadow">@csrf<h2 class="text-xl font-bold">Jabatan</h2><select name="context_type" class="rounded border p-2"><option value="isetial">iSetial</option><option value="dkm">DKM</option></select><select name="masjid_id" class="rounded border p-2"><option value="">Pusat</option>@foreach($masjids as $m)<option value="{{$m->id}}">{{$m->name}}</option>@endforeach</select><input name="name" required placeholder="Nama jabatan" class="rounded border p-2"><input type="number" name="display_order" value="0" min="0" class="rounded border p-2"><button class="rounded bg-emerald-800 p-2 text-white">Tambah jabatan</button></form>
<form method="post" action="{{route('admin.divisions.store')}}" class="grid gap-3 rounded-xl bg-white p-5 shadow">@csrf<h2 class="text-xl font-bold">Divisi</h2><select name="masjid_id" class="rounded border p-2">@if($canGlobal)<option value="">iSetial Wisdom</option>@endif @foreach($masjids as $m)<option value="{{$m->id}}">{{$m->name}}</option>@endforeach</select><input name="name" required placeholder="Nama divisi" class="rounded border p-2"><textarea name="description" placeholder="Deskripsi" class="rounded border p-2"></textarea><button class="rounded bg-emerald-800 p-2 text-white">Tambah divisi</button></form></div>
<form method="post" action="{{route('admin.assignments.store')}}" class="mt-6 grid gap-3 rounded-xl bg-slate-800 p-6 text-white md:grid-cols-3">@csrf<h2 class="text-xl font-bold md:col-span-3">Tempatkan Person pada Jabatan</h2><select name="person_id" required class="rounded border p-2 text-slate-900">@foreach($people as $p)<option value="{{$p->id}}">{{$p->name}}</option>@endforeach</select><select name="organization_period_id" required class="rounded border p-2 text-slate-900">@foreach($periods as $p)<option value="{{$p->id}}">{{$p->name}} · {{$p->masjid?->name ?? 'iSetial'}}</option>@endforeach</select><select name="position_id" required class="rounded border p-2 text-slate-900">@foreach($positions as $p)<option value="{{$p->id}}">{{$p->name}}</option>@endforeach</select><select name="division_id" class="rounded border p-2 text-slate-900"><option value="">Tanpa divisi</option>@foreach($divisions as $d)<option value="{{$d->id}}">{{$d->name}}</option>@endforeach</select><input type="number" name="display_order" value="0" min="0" class="rounded border p-2 text-slate-900"><input type="hidden" name="is_active" value="1"><button class="rounded bg-amber-400 p-2 font-bold text-emerald-950">Tambahkan penempatan</button></form>
<h2 class="mt-10 text-2xl font-black">Penempatan Aktif</h2><div class="mt-4 grid gap-3 md:grid-cols-2">@forelse($assignments as $item)<div class="rounded-xl bg-white p-5 shadow"><b>{{$item->person->name}}</b><p>{{$item->position->name}} @if($item->division) · {{$item->division->name}}@endif</p><small>{{$item->period->name}} · {{$item->masjid?->name ?? 'iSetial Wisdom'}}</small><form method="post" action="{{route('admin.assignments.destroy',$item)}}" class="mt-3">@csrf @method('DELETE')<button class="text-sm text-red-700">Hapus penempatan</button></form></div>@empty<p>Belum ada penempatan.</p>@endforelse</div></div>
@endsection
